data_path: "./data/"
test_size: 0.2
random_state: 1
target_variable: "Ticket Type"

databases:
  - id: 0
    file_name: "cruise_pre.db"
    table_name: "cruise_pre"
    index: "index"
  - id: 1
    file_name: "cruise_post.db"
    table_name: "cruise_post"
    index: "index"

